---
- name: ensure openvpn packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - openvpn
    - easy-rsa
    - openvpn-auth-ldap

- name: ensure openvpn is started and enabled
  service: 
    name: openvpn
    state: started 
    enabled: yes

- name: ensure openvpn is properly shut down for docker
  service: 
    name: openvpn
    state: stopped
  when: openvpn_dockerize_context is defined
