---
- include: docker.yml
  when: openvpn_server_dockerized_deployment

- include: install.yml
  when: not openvpn_server_dockerized_deployment

- include: configure.yml
  when: not openvpn_server_dockerized_deployment 
